/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Zaduzenje;
import forme.macka.IzmjeniMackuForma;
import forme.macka.ObrisiMackuForma;
import forme.macka.UnesiMackuForma;
import forme.volonter.IzmjeniVolonteraForma;
import forme.volonter.ObrisiVolonteraForma;
import forme.volonter.UnesiVolonteraForma;
import forme.zaduzenje.IzvjestajDijalog;
import forme.zaduzenje.PregledZaduzenjaForma;
import forme.zaduzenje.UnosZaduzenjaForma;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import klijentKontroler.KlijentKontroler;
import modeli.ModelTabeleZaduzenje;

/**
 *
 * @author CJ931WT
 */
public class GlavnaForma extends javax.swing.JFrame {
    ModelTabeleZaduzenje mtz;
    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        srediModel();
        centriraj();
        lblKorisnik.setText(KlijentKontroler.getInstance().getTrenutnoUlogovanKorisnik().getKorisnickoIme());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableZaduzenje = new javax.swing.JTable();
        btnIzloguj = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblKorisnik = new javax.swing.JLabel();
        btnUnesiZad = new javax.swing.JButton();
        btnIzvjestaj = new javax.swing.JButton();
        btnDetaljnije = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        meniUnesiZaduzenje = new javax.swing.JMenuBar();
        meniMacka = new javax.swing.JMenu();
        meniUnesiMacku = new javax.swing.JMenuItem();
        meniIzmjeniMacku = new javax.swing.JMenuItem();
        meniObrisiMacku = new javax.swing.JMenuItem();
        meniVolonter = new javax.swing.JMenu();
        meniUnesiVolontera = new javax.swing.JMenuItem();
        meniIzmjeniVolontera = new javax.swing.JMenuItem();
        meniObrisiVolontera = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Evidencija zaduženja u sistemu \"Cat Cafe\"");
        setBackground(java.awt.SystemColor.activeCaption);

        tableZaduzenje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableZaduzenje);

        btnIzloguj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/Odjavljivanje.png"))); // NOI18N
        btnIzloguj.setText("Odjavi se");
        btnIzloguj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzlogujActionPerformed(evt);
            }
        });

        jLabel4.setText("Trenutno ulogovan korisnik:");

        lblKorisnik.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblKorisnik.setText("korisnik");

        btnUnesiZad.setText("Unesi zaduženje");
        btnUnesiZad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiZadActionPerformed(evt);
            }
        });

        btnIzvjestaj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/Izvjestaj.png"))); // NOI18N
        btnIzvjestaj.setText("Kreiraj izvještaj");
        btnIzvjestaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzvjestajActionPerformed(evt);
            }
        });

        btnDetaljnije.setText("Detaljniji prikaz zaduženja");
        btnDetaljnije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljnijeActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/Macka GlavnaForma.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnIzvjestaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnIzloguj, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblKorisnik))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnUnesiZad)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDetaljnije)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblKorisnik))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUnesiZad)
                            .addComponent(btnDetaljnije)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzloguj)
                    .addComponent(btnIzvjestaj))
                .addGap(60, 60, 60))
        );

        meniUnesiZaduzenje.setBorder(null);

        meniMacka.setText("Mačka");

        meniUnesiMacku.setText("Unesi mačku");
        meniUnesiMacku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniUnesiMackuActionPerformed(evt);
            }
        });
        meniMacka.add(meniUnesiMacku);

        meniIzmjeniMacku.setText("Izmjeni mačku");
        meniIzmjeniMacku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniIzmjeniMackuActionPerformed(evt);
            }
        });
        meniMacka.add(meniIzmjeniMacku);

        meniObrisiMacku.setText("Obriši mačku");
        meniObrisiMacku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniObrisiMackuActionPerformed(evt);
            }
        });
        meniMacka.add(meniObrisiMacku);

        meniUnesiZaduzenje.add(meniMacka);

        meniVolonter.setText("Volonter");

        meniUnesiVolontera.setText("Unesi volontera");
        meniUnesiVolontera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniUnesiVolonteraActionPerformed(evt);
            }
        });
        meniVolonter.add(meniUnesiVolontera);

        meniIzmjeniVolontera.setText("Izmjeni volontera");
        meniIzmjeniVolontera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniIzmjeniVolonteraActionPerformed(evt);
            }
        });
        meniVolonter.add(meniIzmjeniVolontera);

        meniObrisiVolontera.setText("Obriši volontera");
        meniObrisiVolontera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniObrisiVolonteraActionPerformed(evt);
            }
        });
        meniVolonter.add(meniObrisiVolontera);

        meniUnesiZaduzenje.add(meniVolonter);

        setJMenuBar(meniUnesiZaduzenje);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meniUnesiMackuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniUnesiMackuActionPerformed
        UnesiMackuForma umf = new UnesiMackuForma();
        umf.setVisible(true);
    }//GEN-LAST:event_meniUnesiMackuActionPerformed

    private void meniIzmjeniMackuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniIzmjeniMackuActionPerformed
        IzmjeniMackuForma imf = new IzmjeniMackuForma();
        imf.setVisible(true);
    }//GEN-LAST:event_meniIzmjeniMackuActionPerformed

    private void meniObrisiMackuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniObrisiMackuActionPerformed
        ObrisiMackuForma omf = new ObrisiMackuForma();
        omf.setVisible(true);
    }//GEN-LAST:event_meniObrisiMackuActionPerformed

    private void meniUnesiVolonteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniUnesiVolonteraActionPerformed
        UnesiVolonteraForma uvf = new UnesiVolonteraForma();
        uvf.setVisible(true);
    }//GEN-LAST:event_meniUnesiVolonteraActionPerformed

    private void meniIzmjeniVolonteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniIzmjeniVolonteraActionPerformed
        IzmjeniVolonteraForma ivf = new IzmjeniVolonteraForma();
        ivf.setVisible(true);
    }//GEN-LAST:event_meniIzmjeniVolonteraActionPerformed

    private void meniObrisiVolonteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniObrisiVolonteraActionPerformed
        ObrisiVolonteraForma ovf = new ObrisiVolonteraForma();
        ovf.setVisible(true);
    }//GEN-LAST:event_meniObrisiVolonteraActionPerformed

    private void btnIzlogujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzlogujActionPerformed
        izlogujKorisnika();
        System.exit(0);
    }//GEN-LAST:event_btnIzlogujActionPerformed
   
    private void btnIzvjestajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzvjestajActionPerformed
        IzvjestajDijalog id = new IzvjestajDijalog(this, true);
        id.setVisible(true);
    }//GEN-LAST:event_btnIzvjestajActionPerformed

    private void btnUnesiZadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiZadActionPerformed
        UnosZaduzenjaForma uzd = new UnosZaduzenjaForma();
        uzd.dodajGF(this);
        uzd.pack();
        uzd.setVisible(true);
    }//GEN-LAST:event_btnUnesiZadActionPerformed

    private void btnDetaljnijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljnijeActionPerformed
        int red = tableZaduzenje.getSelectedRow();

        if (red != -1) {
            ModelTabeleZaduzenje mtz = (ModelTabeleZaduzenje) tableZaduzenje.getModel();
            Zaduzenje z = mtz.dajZaduzenje(red);

            PregledZaduzenjaForma pzd = new PregledZaduzenjaForma();
            pzd.dodajZaduzenje(z);
            pzd.dodajGF(this);
            pzd.srediTabelu();
            pzd.dodajKorisnika(KlijentKontroler.getInstance().getTrenutnoUlogovanKorisnik());
            pzd.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Potrebno je selektovati zaduženje u tabeli.");
            return;
        }
    }//GEN-LAST:event_btnDetaljnijeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetaljnije;
    private javax.swing.JButton btnIzloguj;
    private javax.swing.JButton btnIzvjestaj;
    private javax.swing.JButton btnUnesiZad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKorisnik;
    private javax.swing.JMenuItem meniIzmjeniMacku;
    private javax.swing.JMenuItem meniIzmjeniVolontera;
    private javax.swing.JMenu meniMacka;
    private javax.swing.JMenuItem meniObrisiMacku;
    private javax.swing.JMenuItem meniObrisiVolontera;
    private javax.swing.JMenuItem meniUnesiMacku;
    private javax.swing.JMenuItem meniUnesiVolontera;
    private javax.swing.JMenuBar meniUnesiZaduzenje;
    private javax.swing.JMenu meniVolonter;
    private javax.swing.JTable tableZaduzenje;
    // End of variables declaration//GEN-END:variables

    public void srediModel() {
        ArrayList<Zaduzenje> lista = KlijentKontroler.getInstance().vratiSvaZaduzenja();

        if (lista.isEmpty()) {
            mtz = new ModelTabeleZaduzenje();
        } else {
            mtz = new ModelTabeleZaduzenje(lista);
            mtz.sortiraj();
        }

        tableZaduzenje.setFont(new Font("Arial", Font.PLAIN, 14));
        tableZaduzenje.getTableHeader().setFont(new Font("Arial", Font.PLAIN, 14));
        tableZaduzenje.setModel(mtz);
    }

    private void centriraj() {
        this.setLocationRelativeTo(null);
    }

    private void izlogujKorisnika() {
        String porukaSaServera = KlijentKontroler.getInstance().zavrsiSaRadom();
        JOptionPane.showMessageDialog(this, porukaSaServera, "Uspješno izlogovani", JOptionPane.INFORMATION_MESSAGE);
    }
}
