/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.zaduzenje;

import domen.Korisnik;
import domen.Volonter;
import domen.Zadatak;
import domen.Zaduzenje;
import forme.GlavnaForma;
import forme.zadatak.UnosZadatkaDijalog;
import java.awt.Font;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import klijentKontroler.KlijentKontroler;
import modeli.ModelTabeleZadatak;
import modeli.ModelTabeleZaduzenje;
import transfer.ServerskiTransferObjekat;

/**
 *
 * @author CJ931WT
 */
public class UnosZaduzenjaForma extends javax.swing.JFrame {

    ModelTabeleZaduzenje mtzad;
    ModelTabeleZadatak mtz;
    GlavnaForma gf;

    /**
     * Creates new form UnosZaduzenjaForma
     */
    public UnosZaduzenjaForma() {
        initComponents();
        centriraj();
        popuniKomboVolonter();
        srediTabeluZadataka();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbVolonter = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        btnUnesi = new javax.swing.JButton();
        dateChoserDatum = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableZadatak = new javax.swing.JTable();
        btnDodajZadatak = new javax.swing.JButton();
        btnObrisiZadatak = new javax.swing.JButton();
        btnIzmjeniZadatak = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unos zaduženja");

        jLabel2.setText("Volonter:");

        cmbVolonter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Datum:");

        btnUnesi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/save.png"))); // NOI18N
        btnUnesi.setText("Unesi zaduženje");
        btnUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiActionPerformed(evt);
            }
        });

        tableZadatak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableZadatak);

        btnDodajZadatak.setText("Dodaj zadatak");
        btnDodajZadatak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajZadatakActionPerformed(evt);
            }
        });

        btnObrisiZadatak.setText("Obriši zadatak");
        btnObrisiZadatak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiZadatakActionPerformed(evt);
            }
        });

        btnIzmjeniZadatak.setText("Izmjeni zadatak");
        btnIzmjeniZadatak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmjeniZadatakActionPerformed(evt);
            }
        });

        btnOtkazi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/cancel.png"))); // NOI18N
        btnOtkazi.setText("Otkaži unos");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbVolonter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateChoserDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnObrisiZadatak)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzmjeniZadatak)
                        .addGap(18, 18, 18)
                        .addComponent(btnDodajZadatak))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOtkazi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUnesi)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbVolonter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(dateChoserDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajZadatak)
                    .addComponent(btnObrisiZadatak)
                    .addComponent(btnIzmjeniZadatak))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnesi)
                    .addComponent(btnOtkazi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiActionPerformed
        Date datum = new Date();
        if (dateChoserDatum.getCalendar() != null) {
            datum = dateChoserDatum.getCalendar().getTime();
        } else {
            JOptionPane.showMessageDialog(this, "Sva polja su obavezna");
            return;
        }
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date sadasnji = null;
        try {
            sadasnji = sdf.parse(sdf.format(new Date()));
        } catch (ParseException ex) {
            Logger.getLogger(UnosZaduzenjaForma.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (datum.compareTo(sadasnji) < 0) {
            JOptionPane.showMessageDialog(this, "Zaduženje može biti zadato za danas ili neki od narednih dana.");
            return;
        }

        Volonter volonter = (Volonter) cmbVolonter.getSelectedItem();

        boolean provjera = provjeriVolontera(volonter, datum);
        if (!provjera) {
            JOptionPane.showMessageDialog(this, "Dnevno je moguće zadati volonteru " + volonter.getIme() + " " + volonter.getPrezime() + " jedno zaduženje");
            return;
        }

        Korisnik k = KlijentKontroler.getInstance().getTrenutnoUlogovanKorisnik();
        mtz = (ModelTabeleZadatak) tableZadatak.getModel();
        ArrayList<Zadatak> zadaci = mtz.getLista();
        Zaduzenje z = new Zaduzenje(0, false, datum, volonter, k, zadaci, 0);
        
        for (Zadatak zadatak : zadaci) {
            zadatak.setZaduzenje(z);
        }
        
        ServerskiTransferObjekat sto = KlijentKontroler.getInstance().sacuvajZaduzenje(z);
        JOptionPane.showMessageDialog(this, sto.getPoruka(), "Informacija", JOptionPane.INFORMATION_MESSAGE);

        dateChoserDatum.setDate(new Date());
        cmbVolonter.setSelectedIndex(0);

        if(sto.isUspjesno() != false){
            mtzad.izmjeni(z);
        }
        dispose();
        gf.srediModel();
    }//GEN-LAST:event_btnUnesiActionPerformed

    private void btnDodajZadatakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajZadatakActionPerformed
        UnosZadatkaDijalog dijalog = new UnosZadatkaDijalog(this, true);
        dijalog.setMtz(mtz);
        dijalog.srediZaUnos();
        dijalog.pack();
        dijalog.setVisible(true);
    }//GEN-LAST:event_btnDodajZadatakActionPerformed

    private void btnIzmjeniZadatakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmjeniZadatakActionPerformed
        int red = tableZadatak.getSelectedRow();

        if (red != -1) {
            ModelTabeleZadatak mtz = (ModelTabeleZadatak) tableZadatak.getModel();
            Zadatak z = mtz.vratiZadatak(red);

            UnosZadatkaDijalog dijalog = new UnosZadatkaDijalog(this, true);
            dijalog.dodajZadatak(z);
            dijalog.srediZaIzmjenu();
            dijalog.pack();
            dijalog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Potrebno je selektovati zaduženje u tabeli koju želite da obrišete");
            return;
        }
    }//GEN-LAST:event_btnIzmjeniZadatakActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void btnObrisiZadatakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiZadatakActionPerformed
        int red = tableZadatak.getSelectedRow();

        if (red != -1) {
            ModelTabeleZadatak mtz = (ModelTabeleZadatak) tableZadatak.getModel();
            mtz.izbrisiZadatak(red);
        } else {
            JOptionPane.showMessageDialog(this, "Potrebno je selektovati zaduženje u tabeli koju želite da obrišete");
            return;
        }
    }//GEN-LAST:event_btnObrisiZadatakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnosZaduzenjaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnosZaduzenjaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnosZaduzenjaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnosZaduzenjaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnosZaduzenjaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajZadatak;
    private javax.swing.JButton btnIzmjeniZadatak;
    private javax.swing.JButton btnObrisiZadatak;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnUnesi;
    private javax.swing.JComboBox cmbVolonter;
    private com.toedter.calendar.JDateChooser dateChoserDatum;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableZadatak;
    // End of variables declaration//GEN-END:variables

    private void centriraj() {
        this.setLocationRelativeTo(null);
    }

    private void popuniKomboVolonter() {
        ArrayList<Volonter> lista = KlijentKontroler.getInstance().vratiSveVolontere();
        cmbVolonter.removeAllItems();
        for (Volonter volonter : lista) {
            cmbVolonter.addItem(volonter);
        }
    }

    private boolean provjeriVolontera(Volonter volonter, Date datum) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        ArrayList<Zaduzenje> lista = KlijentKontroler.getInstance().vratiSvaZaduzenja();

        for (Zaduzenje z : lista) {
            Date dat = null;
            try {
                dat = sdf.parse(sdf.format(z.getDatum()));
            } catch (ParseException ex) {
                Logger.getLogger(UnosZaduzenjaForma.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (dat.equals(datum) && z.getVolonter().getVolonterID() == volonter.getVolonterID()) {
                return false;
            }
        }
        return true;
    }

    public void srediTabeluZadataka() {
        mtz = new ModelTabeleZadatak();

        tableZadatak.setFont(new Font("Arial", Font.PLAIN, 14));
        tableZadatak.getTableHeader().setFont(new Font("Arial", Font.PLAIN, 14));
        tableZadatak.setModel(mtz);
    }

    public void dodajZadatak(Zadatak z) {
        ModelTabeleZadatak mtz = (ModelTabeleZadatak) tableZadatak.getModel();
        mtz.dodajZadatak(z);
    }
    
    public void dodajGF(GlavnaForma glavnaForma) {
        gf = glavnaForma;
    }
}
