/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.zadatak;

import domen.Zadatak;
import forme.zaduzenje.PregledZaduzenjaForma;
import javax.swing.JOptionPane;
import modeli.ModelTabeleZadatak;
import tipoviAkcija.Statusi;

/**
 *
 * @author CJ931WT
 */
public class UnosZadatkaDijalog extends javax.swing.JDialog {

    Zadatak zadatak;
    ModelTabeleZadatak mtz;

    /**
     * Creates new form UnosZadatkaDijalog
     */
    public UnosZadatkaDijalog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        centriraj();
        popuniKombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnUnesi = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtVrijeme = new javax.swing.JTextField();
        txtOpis = new javax.swing.JTextField();
        cmbProcjena = new javax.swing.JComboBox<>();
        btnIzmjeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Evidencija zadatka");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel2.setText("Opis zadatka:");

        jLabel4.setText("Potrebno vrijeme (h):");

        btnUnesi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/save.png"))); // NOI18N
        btnUnesi.setText("Unesi zadatak");
        btnUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiActionPerformed(evt);
            }
        });

        btnOtkazi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/cancel.png"))); // NOI18N
        btnOtkazi.setText("Otkaži");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        jLabel1.setText("Procjena:");

        cmbProcjena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnIzmjeni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/change.png"))); // NOI18N
        btnIzmjeni.setText("Izmjeni zadatak");
        btnIzmjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmjeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(btnIzmjeni))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOtkazi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(btnUnesi))
                    .addComponent(txtVrijeme)
                    .addComponent(txtOpis)
                    .addComponent(cmbProcjena, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtOpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtVrijeme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addComponent(cmbProcjena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnesi)
                    .addComponent(btnOtkazi)
                    .addComponent(btnIzmjeni))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiActionPerformed
        if (txtOpis.getText().isEmpty() || txtVrijeme.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sva polja su obavezna");
            return;
        }

        String opis = txtOpis.getText();
        String procjena = (String) cmbProcjena.getSelectedItem();
        int vrijeme = Integer.parseInt(txtVrijeme.getText());

        if (vrijeme < 0) {
            JOptionPane.showMessageDialog(this, "Vrijeme mora imati vrijednost veću od nule");
            return;
        }
        
        int id = mtz.dajID();
        Zadatak z = new Zadatak(id, null, opis, vrijeme, procjena, Statusi.SACUVAJ);
        mtz.dodajZadatak(z);
        this.dispose();
    }//GEN-LAST:event_btnUnesiActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        this.setVisible(false);
        PregledZaduzenjaForma pzf = (PregledZaduzenjaForma) getParent();
        pzf.srediTabelu();
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void btnIzmjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmjeniActionPerformed
        if (txtOpis.getText().isEmpty() || txtVrijeme.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sva polja su obavezna");
            return;
        }

        String opis = txtOpis.getText();
        String procjena = (String) cmbProcjena.getSelectedItem();
        int vrijeme = Integer.parseInt(txtVrijeme.getText());

        if (vrijeme < 0) {
            JOptionPane.showMessageDialog(this, "Vrijeme mora imati vrijednost veću od nule");
            return;
        }
        
        Zadatak z = new Zadatak(zadatak.getRedniBroj(), zadatak.getZaduzenje(), opis, vrijeme, procjena, Statusi.IZMJENI);
        mtz.izmjeni(z);
        this.dispose();
    }//GEN-LAST:event_btnIzmjeniActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnosZadatkaDijalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnosZadatkaDijalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnosZadatkaDijalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnosZadatkaDijalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UnosZadatkaDijalog dialog = new UnosZadatkaDijalog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmjeni;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnUnesi;
    private javax.swing.JComboBox<String> cmbProcjena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtOpis;
    private javax.swing.JTextField txtVrijeme;
    // End of variables declaration//GEN-END:variables

    private void centriraj() {
        this.setLocationRelativeTo(null);
    }

    public void dodajZadatak(Zadatak z) {
        zadatak = z;
        txtOpis.setText(zadatak.getOpisZadatka());
        txtVrijeme.setText(String.valueOf(zadatak.getPotrebnoVrijeme()));
        cmbProcjena.setSelectedItem(zadatak.getProcjena());
    }

    private void popuniKombo() {
        String[] procjena = {"Odlično", "Dobro", "Ok", "Loše", "Veoma loše"};
        cmbProcjena.removeAllItems();

        for (String string : procjena) {
            cmbProcjena.addItem(string);
        }
    }

    public void setMtz(ModelTabeleZadatak mtz) {
        this.mtz = mtz;
    }

    public void srediZaUnos() {
        btnUnesi.setVisible(true);
        btnIzmjeni.setVisible(false);
    }
 
    public void srediZaIzmjenu() {
        btnUnesi.setVisible(false);
        btnIzmjeni.setVisible(true);
    }
}
