/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.volonter;

import domen.Grad;
import domen.Volonter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import klijentKontroler.KlijentKontroler;
import transfer.ServerskiTransferObjekat;

/**
 *
 * @author CJ931WT
 */
public class IzmjeniVolonteraDijalog extends javax.swing.JDialog {
    Volonter volonter;
    /**
     * Creates new form IzmjeniVolonteraDijalog
     */
    public IzmjeniVolonteraDijalog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        centriraj();
        popuniKombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        txtIme = new javax.swing.JTextField();
        txtKontakt = new javax.swing.JTextField();
        btnIzmjena = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();
        cmbGrad = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Izmjeni volontera");

        jLabel1.setText("Ime:");

        jLabel2.setText("Prezime:");

        jLabel3.setText("Kontakt:");

        jLabel4.setText("Grad:");

        btnIzmjena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/change.png"))); // NOI18N
        btnIzmjena.setText("Izmjeni volontera");
        btnIzmjena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmjenaActionPerformed(evt);
            }
        });

        btnOtkazi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/cancel.png"))); // NOI18N
        btnOtkazi.setText("Otkaži izmjenu");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        cmbGrad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOtkazi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(btnIzmjena))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrezime)
                            .addComponent(txtIme)
                            .addComponent(cmbGrad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtKontakt)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmjena)
                    .addComponent(btnOtkazi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmjenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmjenaActionPerformed
        if (txtIme.getText().isEmpty() || txtPrezime.getText().isEmpty() || txtKontakt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sva polja su obavezna");
            return;
        }

        String ime = txtIme.getText().trim();
        String prezime = txtPrezime.getText().trim();
        String kontakt = txtKontakt.getText().trim();

        boolean formatImena = provjeriFormat(ime);
        boolean formatPrezimena = provjeriFormat(prezime);
        boolean formatKontakta = provjeriFormatKontakta(kontakt);

        if(!formatImena || !formatPrezimena){
            JOptionPane.showMessageDialog(this, "Ime/Prezime se sastoje samo od slova i razmaka, ispraviti unijeto ime/prezime");
            return;
        }

        if(!formatKontakta){
            JOptionPane.showMessageDialog(this, "Kontakt se sastoji od broja i specijalnih znakova '/' i '-', ispraviti unos");
            return;
        }

        if (!volonter.getKontakt().equals(kontakt)) {
            boolean okKontakt = provjeriKontakt(kontakt);
            if (!okKontakt) {
                JOptionPane.showMessageDialog(this, "Kontakt već postoji u bazi");
                return;
            }
        }

        Grad g = (Grad) cmbGrad.getSelectedItem();
        Volonter vol = new Volonter(volonter.getVolonterID(), ime, prezime, kontakt, g, null);
        ServerskiTransferObjekat sto = KlijentKontroler.getInstance().izmjeniVolontera(vol);
        JOptionPane.showMessageDialog(this, sto.getPoruka(), "Informacija", JOptionPane.INFORMATION_MESSAGE);
        IzmjeniVolonteraForma ivf = (IzmjeniVolonteraForma) getParent();
        ivf.srediModel();
        this.dispose();
    }//GEN-LAST:event_btnIzmjenaActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnOtkaziActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IzmjeniVolonteraDijalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IzmjeniVolonteraDijalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IzmjeniVolonteraDijalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IzmjeniVolonteraDijalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IzmjeniVolonteraDijalog dialog = new IzmjeniVolonteraDijalog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmjena;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JComboBox cmbGrad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtKontakt;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables
    
    private void centriraj() {
        this.setLocationRelativeTo(null);
    }

    private void popuniKombo() {
        ArrayList<Grad> listaGradova = KlijentKontroler.getInstance().vratiGradove();

        cmbGrad.removeAllItems();
        for (Grad g : listaGradova) {
            cmbGrad.addItem(g);
        }
    }
    
    private boolean provjeriKontakt(String kontakt) {
        ArrayList<Volonter> listaVolontera = KlijentKontroler.getInstance().vratiSveVolontere();
        for (Volonter v : listaVolontera) {
            if (v.getKontakt().equals(kontakt)) {
                return false;
            }
        }
        return true;
    }

    private boolean provjeriFormat(String ime) {
        int slovo = 0;
        int razmak = 0;

        for (int i = 0; i < ime.length(); i++) {
            char c = ime.charAt(i);
            if (Character.isLetter(c) || c == ' ') {
                continue;
            }
            return false;
        }
        return true;
    }

    private boolean provjeriFormatKontakta(String kontakt) {
        for (int i = 0; i < kontakt.length(); i++) {
            char c = kontakt.charAt(i);
            if (Character.isDigit(c) || c == '/' || c == '-') {
                continue;
            }
            return false;
        }
        return true;
    }

    void dodajVolontera(Volonter v) {
        volonter = v;
        txtIme.setText(v.getIme());
        txtPrezime.setText(v.getPrezime());
        txtKontakt.setText(v.getKontakt());
        cmbGrad.setSelectedItem(v.getGrad());
    }
}
