/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.volonter;

import domen.Volonter;
import java.awt.Font;
import static java.lang.Character.isDigit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import klijentKontroler.KlijentKontroler;
import modeli.ModelTabeleVolonter;

/**
 *
 * @author CJ931WT
 */
public class IzmjeniVolonteraForma extends javax.swing.JFrame {

    /**
     * Creates new form IzmjeniVolonteraForma
     */
    public IzmjeniVolonteraForma() {
        initComponents();
        centriraj();
        srediModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVolonter = new javax.swing.JTable();
        btnIzmjeni = new javax.swing.JButton();
        btnOtkazi = new javax.swing.JButton();
        txtPrezime = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        btnPonisti = new javax.swing.JButton();
        checkIme = new javax.swing.JCheckBox();
        checkPrezime = new javax.swing.JCheckBox();
        txtIme = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Izmjena volontera");

        tableVolonter.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tableVolonter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableVolonter);

        btnIzmjeni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/change.png"))); // NOI18N
        btnIzmjeni.setText("Izmjeni volontera");
        btnIzmjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmjeniActionPerformed(evt);
            }
        });

        btnOtkazi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/cancel.png"))); // NOI18N
        btnOtkazi.setText("Otkaži izmjene");
        btnOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziActionPerformed(evt);
            }
        });

        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        btnPonisti.setText("Poništi");
        btnPonisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPonistiActionPerformed(evt);
            }
        });

        checkIme.setText("Ime volontera:");

        checkPrezime.setText("Prezime volontera:");
        checkPrezime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPrezimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPonisti)
                                .addGap(18, 18, 18)
                                .addComponent(btnPretrazi))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnOtkazi)
                                .addGap(18, 18, 18)
                                .addComponent(btnIzmjeni))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkPrezime)
                            .addComponent(checkIme))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIme)
                            .addComponent(txtPrezime))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkIme)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkPrezime)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPretrazi)
                    .addComponent(btnPonisti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmjeni)
                    .addComponent(btnOtkazi))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmjeniActionPerformed
        int red = tableVolonter.getSelectedRow();

        if (red != -1) {
            ModelTabeleVolonter mtv = (ModelTabeleVolonter) tableVolonter.getModel();
            Volonter v = mtv.dajVolontera(red);

            IzmjeniVolonteraDijalog ivz = new IzmjeniVolonteraDijalog(this, true);
            ivz.dodajVolontera(v);
            ivz.pack();
            ivz.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Potrebno je selektovati volontera u tabeli koju želite da izmjenite");
            return;
        }
    }//GEN-LAST:event_btnIzmjeniActionPerformed

    private void btnOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnOtkaziActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        if ((!checkIme.isSelected() && !checkPrezime.isSelected()) || (checkIme.isSelected() && txtIme.getText().isEmpty())
                || (checkPrezime.isSelected() && txtPrezime.getText().isEmpty())) {
            JOptionPane.showMessageDialog(this, "Za pretragu je potrebno unijeti ime i/ili prezime volontera!");
            return;
        }

        if (checkPrezime.isSelected() && checkIme.isSelected()) {
            String prezime = txtPrezime.getText().trim();

            for (int i = 0; i < prezime.length(); i++) {
                char provjera = prezime.charAt(i);
                if (isDigit(provjera)) {
                    JOptionPane.showMessageDialog(this, "Prezime ne smije da sadrži brojeve");
                    return;
                }
            }

            String ime = txtIme.getText().trim();

            for (int i = 0; i < ime.length(); i++) {
                char provjera = ime.charAt(i);
                if (isDigit(provjera)) {
                    JOptionPane.showMessageDialog(this, "Ime ne smije da sadrži brojeve");
                    return;
                }
            }

            ArrayList<String> kriterijum = new ArrayList<>();
            kriterijum.add(ime);
            kriterijum.add(prezime);
            Volonter v = new Volonter();
            v.setKriterijumPretrage(kriterijum);

            ArrayList<Volonter> pretraga = KlijentKontroler.getInstance().pretraziVolontere(v);
            srediFormuPoslijePretrage(pretraga);
        }

        if (checkPrezime.isSelected() && !checkIme.isSelected()) {
            String prezime = txtPrezime.getText().trim();

            for (int i = 0; i < prezime.length(); i++) {
                char provjera = prezime.charAt(i);
                if (isDigit(provjera)) {
                    JOptionPane.showMessageDialog(this, "Prezime ne smije da sadrži brojeve");
                    return;
                }
            }

            ArrayList<String> kriterijum = new ArrayList<>();
            kriterijum.add(new String());
            kriterijum.add(prezime);
            Volonter v = new Volonter();
            v.setKriterijumPretrage(kriterijum);

            ArrayList<Volonter> pretraga = KlijentKontroler.getInstance().pretraziVolontere(v);
            srediFormuPoslijePretrage(pretraga);
        }

        if (checkIme.isSelected()) {
            String ime = txtIme.getText().trim();

            for (int i = 0; i < ime.length(); i++) {
                char provjera = ime.charAt(i);
                if (isDigit(provjera)) {
                    JOptionPane.showMessageDialog(this, "Ime ne smije da sadrži brojeve");
                    return;
                }
            }

            ArrayList<String> kriterijum = new ArrayList<>();
            kriterijum.add(ime);
            kriterijum.add(new String());
            Volonter v = new Volonter();
            v.setKriterijumPretrage(kriterijum);

            ArrayList<Volonter> pretraga = KlijentKontroler.getInstance().pretraziVolontere(v);
            srediFormuPoslijePretrage(pretraga);
        }
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnPonistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPonistiActionPerformed
        srediModel();
    }//GEN-LAST:event_btnPonistiActionPerformed

    private void checkPrezimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPrezimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkPrezimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IzmjeniVolonteraForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IzmjeniVolonteraForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IzmjeniVolonteraForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IzmjeniVolonteraForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IzmjeniVolonteraForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmjeni;
    private javax.swing.JButton btnOtkazi;
    private javax.swing.JButton btnPonisti;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JCheckBox checkIme;
    private javax.swing.JCheckBox checkPrezime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableVolonter;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private void centriraj() {
        this.setLocationRelativeTo(null);
    }

    public void srediModel() {
        ArrayList<Volonter> volonteri = KlijentKontroler.getInstance().vratiSveVolontere();

        ModelTabeleVolonter mtm = new ModelTabeleVolonter(volonteri);

        tableVolonter.setFont(new Font("Arial", Font.PLAIN, 14));
        tableVolonter.getTableHeader().setFont(new Font("Arial", Font.PLAIN, 14));
        tableVolonter.setModel(mtm);
    }

    private void srediFormuPoslijePretrage(ArrayList<Volonter> pretraga) {
        ModelTabeleVolonter mtv = (ModelTabeleVolonter) tableVolonter.getModel();
        mtv.setLista(pretraga);
    }
}
