/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.volonter;

import domen.Volonter;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import klijentKontroler.KlijentKontroler;
import modeli.ModelTabeleVolonter;

/**
 *
 * @author CJ931WT
 */
public class ObrisiVolonteraForma extends javax.swing.JFrame {

    /**
     * Creates new form ObrisiVolonteraForma
     */
    public ObrisiVolonteraForma() {
        initComponents();
        centriraj();
        srediModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tableVolonter = new javax.swing.JTable();
        btnBrisanje = new javax.swing.JButton();
        btnOtkaziBrisanje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Brisanje volontera");

        tableVolonter.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tableVolonter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane10.setViewportView(tableVolonter);

        btnBrisanje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/delete.png"))); // NOI18N
        btnBrisanje.setText("Obriši volontera");
        btnBrisanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrisanjeActionPerformed(evt);
            }
        });

        btnOtkaziBrisanje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/cancel.png"))); // NOI18N
        btnOtkaziBrisanje.setText("Otkaži brisanje");
        btnOtkaziBrisanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziBrisanjeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOtkaziBrisanje)
                        .addGap(18, 18, 18)
                        .addComponent(btnBrisanje)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrisanje)
                    .addComponent(btnOtkaziBrisanje))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrisanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrisanjeActionPerformed
        int red = tableVolonter.getSelectedRow();

        if (red != -1) {
            ModelTabeleVolonter mtv = (ModelTabeleVolonter) tableVolonter.getModel();
            Volonter v = mtv.dajVolontera(red);
           
            BrisanjeVolonteraDijalog dijalog = new BrisanjeVolonteraDijalog(this, true);
            dijalog.dodajVolontera(v);
            dijalog.pack();
            dijalog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Potrebno je selektovati mačku u tabeli koju želite da obrišete");
            return;
        }
    }//GEN-LAST:event_btnBrisanjeActionPerformed

    private void btnOtkaziBrisanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziBrisanjeActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnOtkaziBrisanjeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObrisiVolonteraForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObrisiVolonteraForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObrisiVolonteraForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObrisiVolonteraForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObrisiVolonteraForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrisanje;
    private javax.swing.JButton btnOtkaziBrisanje;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JTable tableVolonter;
    // End of variables declaration//GEN-END:variables
    
    private void centriraj() {
        this.setLocationRelativeTo(null);
    }

    public void srediModel() {
        ArrayList<Volonter> volonteri = KlijentKontroler.getInstance().vratiSveVolontere();

        ModelTabeleVolonter mtm = new ModelTabeleVolonter(volonteri);

        tableVolonter.setFont(new Font("Arial", Font.PLAIN, 14));
        tableVolonter.getTableHeader().setFont(new Font("Arial", Font.PLAIN, 14));
        tableVolonter.setModel(mtm);
    }

    private void srediFormuPoslijeBrisanja(ArrayList<Volonter> pretraga) {
        ModelTabeleVolonter mtv = (ModelTabeleVolonter) tableVolonter.getModel();
        mtv.setLista(pretraga);
    }

}
